### ISSUE TITLE
✨ Chore: 초기 프로젝트 세팅

### ISSUE THREAD

**Issue by GraceKim527** [Tasty-Inventory/Tasty-Inventory_FE#2]
## ✨ About Issue ✨

협업을 위한 초기 프로젝트를 세팅합니다.

### 프로젝트 초기 설정(CRA 사용)
- npm 버전 10.2.3
- ESLint, Prettier 설치
- React
- React-Router-dom
- Styled-components

<br>

## ✅ Todo

- [x] 프로젝트 패키지 설치
- [x] 폴더 구조 세부화
- [x] reset.css 추가
- [x] font 추가

**Comment by GraceKim527** [comment]
## 폴더 구조 선택
"해당 프로젝트에서는 다음과 같은 폴더를 위주로 사용 예정입니다."

- components = 컴포넌트
- pages = 페이지
- hooks = hooks
- style = 스타일
- assets = 이미지, 아이콘 등 정적 파일
- utils = 유틸 함수
- api = api 목록
- store = 전역 상태
