### ISSUE TITLE
👷 Deploy: Git Actions을 이용한 CI/CD 구축(+Vercel)

### ISSUE THREAD

**Issue by GraceKim527** [Tasty-Inventory/Tasty-Inventory_FE#3]
## ✨ About Issue ✨

- 바로 빌드 및 배포를 할 수 있도록 파이프라인을 구성합니다. 

<br>

## ✅ Todo

- [x] Vercel 배포 공부
- [x] CI/CD 세팅
- [x] CI/CD 세팅 테스트
